[[redirects]]
  from = "/itunes-api/*"
  to = "https://itunes.apple.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/mockServiceWorker.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
